project_name: grpcp
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/grpcp/main.go
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: "auto"
